# Generated by Django 2.2.5 on 2019-09-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='sala',
            field=models.CharField(choices=[('Obreiro', 'Obreiros'), ('Mulheres', 'Mulheres'), ('Jovens', 'Jovens'), ('Discipulado', 'Discipulado')], max_length=20),
        ),
    ]
